cmd/workflow-engine/app/bootstrap_test.go
glide.lock
glide.yaml
pkg/controller/BUILD.bazel
pkg/controller/query/BUILD.bazel
pkg/controller/server.go
pkg/projector/BUILD.bazel
pkg/projector/project/BUILD.bazel
pkg/projector/project/invocation/BUILD.bazel
pkg/projector/project/invocation/projector.go
pkg/projector/project/types.go
pkg/projector/project/workflow/BUILD.bazel
pkg/projector/project/workflow/projector.go
pkg/projector/projection.go
pkg/util/labels/BUILD.bazel
pkg/util/labels/kubelabels/BUILD.bazel
pkg/util/labels/kubelabels/kubelabels.go
pkg/util/labels/kubelabels/kubelabels_test.go
pkg/util/labels/labels.go
pkg/util/pubsub/BUILD.bazel
pkg/util/pubsub/pubsub.go
pkg/util/pubsub/pubsub_test.go

This PR replaces the original simple gochannel-based notification functionality with a more generic PubSub-like solution. This label-based approach, allows subscribers to indicate in which events they are interested. This solves the issue that the controller received notifications for events it can't do anything about. 
In the future the NATS client can also be refactored to use this package instead.

Improve controller notifications

---

examples/simple/echowhale.wf.json
examples/simple/fortunewhale.wf.json
pkg/controller/query/BUILD.bazel
pkg/controller/query/expr.go
pkg/controller/query/expr_test.go

This PR adds some safety to the Otto JavaScript interpreter by placing a limit on the execution time (100ms) and ensure that there is not way that functions can share scope.
Flyby:
- updated examples

Timeout + scope isolation in Otto interpreter

---

glide.lock
glide.yaml
pkg/util/functionref/parserformatter.go
pkg/util/functionref/parserformatter_test.go

This utility is needed to be able to resolve a task FunctionRef to the corresponding fission.FunctionRef.

Add fission.FunctionRef parser/formatter

---

INSTALL.md
README.md
charts/fission-workflows/templates/NOTES.txt
charts/fission-workflows/templates/deployment.yaml
charts/fission-workflows/values.yaml
compiling.md

This allows a bit more convenient deployment of locally compiled instances. (see the update to compiling.md for example)

Extract tag from helm deployment

---

build/docker.sh
build/env/Dockerfile
charts/fission-workflows/Chart.yaml
charts/fission-workflows/templates/deployment.yaml
charts/fission-workflows/values.yaml
cmd/fission-workflows-bundle/bundle/bundle.go
cmd/fission-workflows-bundle/main.go
cmd/wfcli/main.go
compiling.md
glide.lock
glide.yaml
pkg/fnenv/fission/resolver.go
pkg/fnenv/fission/runtime.go
pkg/version/version.go

Update the dependency on fission to include https://github.com/fission/fission/commit/b2678783b63b4dccda8e6b02ca1adf292e1bb183
This involves
- replacing references to k8s client to use apimachinery version
- renaming poolmgr references to executor
- fix golang.com/x/text to avoid a conflicting dependency

Update Fission dependency

---

charts/fission-workflows/templates/deployment.yaml
charts/fission-workflows/values.yaml
cmd/fission-workflows-bundle/bundle/bundle.go
compiling.md
pkg/api/workflow/parse/resolver.go
pkg/controller/invocation.go
pkg/controller/workflow.go
pkg/fnenv/fission/resolver.go
pkg/util/backoff/backoff.go
pkg/util/backoff/backoff_test.go

This PR adds environment variables to the Fission Workflow environment in the (Helm) deployment.
Flybys:
- Fixes a bug in the backoff utility
- improves logging and error handling in a couple of places

Add environment variables to deployment

---

examples/whales/README.md
examples/whales/deploy.sh
examples/whales/echowhale.wf.yaml
examples/whales/fortune.sh
examples/whales/fortunewhale.wf.yaml
examples/whales/maybewhale.wf.yaml
examples/whales/metadatawhale.wf.yaml
examples/whales/nestedwhale.wf.yaml
examples/whales/whalesay.sh
pkg/fnenv/fission/envproxy.go
pkg/fnenv/fission/runtime.go
pkg/types/types.go

This PR adds support for users to specify headers (and queries)
The main advantage of using headers is that those explicitly do not get recorded anywhere. They are specific to a task and do not get propagated through 
It currently uses a quick experimental format detecting inputs with a key `header_*` as headers and `query_*` as query params. In the future it might be an option to change it to an object-based format:
```
headers:
key: val
```
Or support both ways of defining headers.
As flybys:
- User can force the Content type of the request
- Updated / improved the documentation of the examples
- Added a util function to limit the printing of a TypedValue to avoid cluttering of the UI.

Add support for inputs specifying task metadata

---

.travis.yml
glide.lock
pkg/api/workflow/parse/resolver.go
test/e2e/traptest.sh
test/e2e/travis-buildtest.sh
test/e2e/travis-kube-setup.sh
test/runtests.sh

Part 1 of Travis e2e integration: setting up access to GKE cluster
As a flyby, a race condition was fixed in the resolving of tasks in the workflow parser

Integrate e2e with Travis/GKE

---

Docs/input-expressions.md
pkg/controller/expr/expr.go
pkg/controller/expr/expr_test.go
pkg/controller/expr/functions.go
pkg/controller/expr/scope.go
pkg/controller/invocation.go

This PR adds the initial draft documentation regarding the input expression concept, containing an explanation of the general idea, data model and various examples.
Additionally, it cleans up the expr package a bit. Removing the need for multiple scopes, in favor of a single taskId reference to be passed as a variable to Otto.

Add input expressions documentation

---

glide.lock
glide.yaml
hack/deploy.sh
hack/minikube.sh
hack/verify-workflows.sh
pkg/types/graph/graph.go
pkg/types/types.go
pkg/types/validate/validate.go
pkg/types/validate/validate_test.go

This PR adds two related packages. First this change introduces a Gonum-based graph implementation for improved performance and easier access to advanced, well-tested graph functionality. In a future PR the implicit graph implementation in the scheduler will be replaced with this one.
Partly using this new graphing support to detect circular dependencies, this PR also adds a new validation package. It aims to replace the existing ad-hoc implementation with a more structured, and consistent API. Likewise, in a future PR the current validation will be replaced with this `validation` package.

Add improved graph and validation support

---

.Dockerignore
.gitignore
.travis.yml
build/.gitignore
build/Dockerfile
build/build-env/Dockerfile
build/build-osx.sh
build/build-windows.sh
build/bundle/Dockerfile
build/docker.sh
build/runtime-env/Dockerfile
build/wfcli/Dockerfile
hack/release.sh
test/e2e/buildtest.sh

Removed the need for passing and copying the binaries everywhere by using docker multi-stage builds. Additionally, the specialized images (e.g. the ones adapted for Fission environment spec depend on the core bundle image.

Improve (docker) build scripts

---

pkg/controller/controller.go
pkg/controller/invocation/controller.go
pkg/controller/workflow/controller.go

This PR bumps the controller tick speed from 1 sec to 100 ms and removes the verbose "not being able to access" messages from the logs.

Bump controller tick speed to 100 ms

---

INSTALL.md

This PR adds (installation) documentation for the `wfcli` tool.

Add installation instructions for wfcli client

---

INSTALL.md
README.md
compiling.md

This PR adds a missing instruction to the installation docs. Moreover, it fixes a couple of awkward sentences in the top-level documents.
This addresses #133

Add chmod line to the installation instructions

---

build/build-env/defaultBuild.sh

Fixes #139 
* Fix variable errors, use $
* Only scan for `*.wf.yaml` files as archive may contain other `*.yaml` files (happened in real use case)
* Fix parse call by removing wrong `>` redirection call

Fix bash variable errors at workflow builder cmd

---

.gitignore
pkg/api/api.go
pkg/api/dynamic.go
pkg/api/invocation.go
pkg/api/task.go
pkg/api/workflow.go
pkg/apiserver/admin.go
pkg/apiserver/apiserver.go
pkg/apiserver/invocation.go
pkg/apiserver/workflow.go
pkg/types/typedvalues/controlflow.go
pkg/types/validate/validate.go

To ensure that HTTP response statuses better fit the actual error, this PR converts errors explicitely to gRPC status errors. This ensures that validation errors get converted to 402s, instead of 500s.

Match validation errors to IllegalArgument HTTP statuses

---

cmd/fission-workflows-bundle/main.go

Currently termination can only be forced (as the context that is used to determine cancellation is never actually cancelled). This PR closes the context on termination signals from the OS.
This should reduce the runtime of tests especially (as a significant amount of time is spent on waiting for workflows process to finish after a SIGTERM.

Listen to system termination signals

---

cmd/fission-workflows-bundle/bundle/bundle.go
pkg/controller/invocation/controller.go
pkg/controller/workflow/controller.go
pkg/fes/backend/mem/mem_test.go
pkg/fes/proto.go
pkg/util/labels/labels.go
pkg/util/pubsub/pubsub.go
pkg/util/pubsub/pubsub_test.go

As part of a cleanup of stale, but as-good-as-finished, PRs - this PR cleans up the labels package. It renames some of the functions and structs in package to better fitting names and adds documentation throughout.  Additionally it removes the need for our custom struct-to-map functions by using the `structs` package.

Cleanup labels package

---

pkg/fnenv/common/httpconv/httpconv.go

The `Content-Length` header in Golang `http` requests is [only set when using `NewRequest`](https://github.com/golang/go/blob/fced03a5c6dd22dd486106e3dd116510c28c6e4a/src/net/http/request.go#L565-L574) (instead of being set when the actual request is send). This means that when setting the Body field after the initial construction of the request, the content-length will remain unset unless explicitly set by the user.
To fix this issue, this PR explicitly sets the contentLength when setting the body.
As a flyby this PR also changes the default method to be used for fission requests to `post`, as this used to be (and still should be) the default. 
cc @soamvasani

Set content-length when setting body

---

build/Dockerfile
build/docker.sh

This add a input flag `NOBUILD` to  `build/docker.sh`, to allow users to build the bundle out of docker build stage.

add NOBUILD ARG to script

---

Docs/functions.md
examples/demo-kubecon2018/fortunewhale.wf.yaml
examples/misc/deploy.sh
examples/misc/dump.sh
examples/misc/fission-inputs.wf.yaml
examples/misc/fissioninputs.wf.yaml
examples/whales/deploy.sh
examples/whales/echowhale.wf.yaml
examples/whales/foreachwhale.wf.yaml
examples/whales/fortunewhale.wf.yaml
examples/whales/httpwhale.wf.yaml
examples/whales/maybewhale.wf.yaml
examples/whales/nestedwhale.wf.yaml
examples/whales/scopedwhale.wf.yaml
pkg/fnenv/common/httpconv/httpconv.go
pkg/types/extensions.go
test/e2e/buildtest.sh
test/e2e/tests/test_fission_params.sh
test/e2e/tests/test_inputs.sh

This PR fixes usability issues when using YAML  to define a workflow. To improve the usability it...
- Fixes the usage of `body` to input the body for a Fission function.
- In documentation promotes using `body` over `default` when inputting the body of a fission function.
- Adds `body` usage to all examples to clarify the usage of the `body` input.
- Adds a test to e2e that tests for setting the method, headers, query and body for a fission function.

YAML API improvements

---

charts/fission-workflows/templates/deployment.yaml
charts/fission-workflows/values.yaml

This is to add configurable runtime parameters, such as grace period, debug enable, to chart.

add configurable runtime parameters to chart

---

.travis.yml
charts/fission-workflows/templates/deployment.yaml
charts/fission-workflows/values.yaml
examples/workflows-env.yaml
hack/codegen-helm.sh
pkg/apiserver/invocation.go
pkg/fnenv/workflows/workflows.go

Added environment as a kubernetes resource definition

---

pkg/fnenv/fission/runtime.go

The IO buffer Body of HTTP response should be closed when exiting the function.

close response body

---

pkg/fnenv/fission/envproxy.go

HTTP handler of health checking seems to be configured `handleSpecialize` incorrectly.

Fix HTTP handler of health checking

---

glide.lock
glide.yaml
pkg/api/api.go
pkg/api/task.go
pkg/controller/invocation/actions.go
pkg/types/extensions.go
test/integration/bundle/bundle_test.go
test/integration/nats/nats_test.go

This change enables support for the 'output' field of task definitions.
If set this output field will replace the actual output of the function.
In case the output field contains an expression, the expression will be
resolved using the current state of the invocation.

Support output transformations

---

pkg/controller/invocation/rules.go

This improves the mechanism inside the invocation rule to check if all tasks are
completed.
Some temp variables are removed away, and it should check the task status in each loop,
to return the result when it is the right condition.
This enhance readability and the performance a little.

improve mechanism inside invocation rule

---

cmd/fission-workflows-bundle/bundle/bundle.go
glide.lock
glide.yaml
pkg/apiserver/httpclient/httpclient.go
pkg/apiserver/invocation.go
pkg/fes/backend/mem/mem.go
pkg/fes/backend/mem/mem_test.go
pkg/fes/backend/nats/client.go
pkg/fes/entity.go
pkg/fes/types.go
pkg/fnenv/fission/runtime.go
pkg/fnenv/native/builtin/if.go
pkg/fnenv/native/builtin/switch.go
pkg/types/typedvalues/httpconv/httpconv.go
pkg/types/typedvalues/typedvalues.go
test/integration/nats/nats_test.go

Currently, originally intended for simple development and testing, this backend consisted solely out of a map containing all events. As it would never remove old/completed invocations/workflows this meant that over time the event store would hog up more and more memory until an inevitable OOM occurred.
This PR has as a goal to make the in-memory event store feasible for longer-term or more intensive deployments, such as benchmarks and use cases that don't require persistence of events. The solution in this PR is to use an approach akin to TinyLFU for caches. The store is assigned specific limits to the number of entities (`n`) it contains, which are contained in two segments:
- **store** which contains all currently active event streams, which under no circumstance should be deleted.
- …

Constrain memory usage in the in-memory backend

---

test/e2e/cleanup.sh
test/e2e/tests/test_inputs.sh

This PR aims to speed up the cleanup process (which in some cases took up the majority of the test runtime) by forcing the deletion of the kubernetes objects. This should avoid Kubernetes waiting extensively for the graceful shutdown of objects.

Force k8s object removal in e2e cleanup

---

cmd/fission-workflows-bundle/bundle/bundle.go
pkg/api/store/store.go
pkg/apiserver/apiserver.go
pkg/apiserver/apiserver.pb.go
pkg/apiserver/invocation.go
pkg/apiserver/workflow.go
pkg/controller/invocation/controller.go
pkg/controller/invocation/controller_test.go
pkg/controller/workflow/controller.go
pkg/controller/workflow/controller_test.go
pkg/fes/types.go
pkg/fnenv/workflows/workflows.go
pkg/fnenv/workflows/workflows_test.go

Currently, all access to the workflow and invocation caches happens through the generic/untyped` fes.CacheReader` interface. This requires consumers to perform type assertions and conversions every time they need to access the caches, and makes it easy to confuse the two caches. 
This PR adds two simple wrappers on top of the fes.CacheReader interface: one for workflows, and one for invocations. These allow consumers to retrieve the workflows and invocations without the risks and verboseness of the type assertions on every access.
Before merging:

Added invocation and workflow stores for typed entity retrieval

---

Docs/development.md
cmd/fission-workflows-bundle/bundle/bundle.go
pkg/controller/actions.go
pkg/controller/evaluation.go
pkg/controller/evaluation_test.go
pkg/controller/invocation/actions.go
pkg/controller/invocation/controller.go
pkg/fnenv/fission/runtime.go
pkg/fnenv/native/native.go
pkg/fnenv/workflows/workflows.go
pkg/parse/parser.go

This PR improves the opentracing support in workflows in multiple ways:
- it adds a couple of additional spans to trace: controller evaluations, fission function calls, workflow calls.
- it adds logs to spans, which include (in debug mode) all inputs, outputs and expressions.
- it adds tags to the spans, including the function references, workflow ids, task ids, and statuses, to enable searching for specific tasks.
- Adds documentation on how to use opentracing for local development.

Improved opentracing support

---

build/Dockerfile

The fission-workflows-bundle image has two functions: 
1) it serves as a container of all binaries of the same build. Other images use this image to grab a specific binary from it and modify it according to the use case.
2) for the plain fission workflows server, the fission-workflows-bundle is used directly.
The last use case is not as straightforward as it could be right now. To run a basic version of the workflow-engine you need to modify both the ENTRYPOINT and CMD on a `docker run`, which is cumbersome to do from the top of your head.
This PR solves this by adding a ENTRYPOINT and CMD to the Dockerfile. These are intended as sensible defaults to allow users to run an instance as simple as: `docker run -p 5555:5555 -p 8080:8080 fission/fission-workflows-bundle`. Advanced users and the …

Add default CMD and ENTRYPOINT to bundle image

---

pkg/apiserver/apiserver.go
pkg/apiserver/client.go
test/integration/bundle/bundle_test.go

Although bundled together on the same server, the apiserver consists of three separate gRPC servers. This also means that we have three different generated gRPC clients. 
For convenience and clarity this PR adds a monolithic Client to the apiserver package, which wraps the three generated gRPC clients.

Add a single gRPC client 

---

charts/fission-workflows/templates/deployment.yaml

This fixes the problem that outdated images might be used in the CI environment. See #228.

Add missing PullPolicy to workflow deployment

---

pkg/parse/parser.go

Both bugs occur when multiple parsers are being tried to parse a workflow definition. There were a couple of variables that were not updated or reset when a parser failed and another one is being tried.

Fix minor bugs in workflow parser

---

charts/fission-workflows/templates/deployment.yaml
charts/fission-workflows/values.yaml

PR to fix the CrashLoopBackOff when you install the fission-workflow helm chart

Making Jaeger Tracing image configurable
